### ISSUE TITLE
Error when loading component

### ISSUE THREAD

**Issue by whscholtens** [pijiulaoshi/ha_philipssomneo#1]
Hi,

thanks for making this custom component. However, it's not working for me:

`2020-12-29 08:50:12 ERROR (MainThread) [homeassistant.setup] Setup failed for philips_somneo: Unable to import component: cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
`

Running HA in Docker on a RPi4.

**Comment by SKrooshof** [comment]
@whscholtens , change the constant name UNIT_PERCENTAGE to PERCENTAGE, that should work.

**Comment by pijiulaoshi** [comment]
@SKrooshof Thanks! I haven't been maintaining this very well, since I thought no one was actually using this component (besides me). I have fixed the issue.
